name: "RealHTTP CI"
on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
  
concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  SPM:
    name: SPM Unit Tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        swift: ["5.5"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
  test:
    runs-on: macOS-latest
    env:
      SCHEME: RealHTTP
      XCODE_PATH: $(xcode-select --print-path)
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 11,OS=13.7

          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 13,OS=latest

          - sdk: macosx
            destination: arch=x86_64

    steps:
    - uses: actions/checkout@v1

    - name: Link to 13.7 Simulators
      run: |
        echo "XCode Path is: $XCODE_PATH"
        echo "Creating Runtimes folder if needed..."
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        echo "Creating symlink of the iOS 13.7 runtime..."
        sudo ln -s $XCODE_PATH/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.7.simruntime

    - name: List SDKs and Devices
      run: xcodebuild -showsdks;

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage NO \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
